### ISSUE TITLE
Ability to turn off code completion via config

### ISSUE THREAD

**Issue by adrum** [jrrdnx/expressionengine#7]
I don't really care for this and would just like the syntax highlighting.

Anyway to optionally disable this?

Source: https://github.com/jrrdnx/expressionengine/issues/5

**Comment by adrum** [comment]
More info. When writing JavaScript and creating a new function, my single bracket gets suggested an EE recommendation. It would be cool if you could only allow suggestions within the scope of HTML.

**Comment by jrrdnx** [comment]
There's an `expressionengine.suggest.basic` setting set to 'true' by default, you can change this to 'false'.

I'm currently researching if/how it's possible to keep default html/javascript/php completions and formatting as-is, and only apply the ExpressionEngine completions and formatting when applicable. If anyone has any tips or suggestions on this, it'd be much appreciated!

**Comment by adrum** [comment]
Whoops! Totally missed it. Thanks @jrrdnx
